version: '3.8'

services:
  spatial-eeg:
    build: .
    container_name: spatial-eeg-system
    volumes:
      # Persist logs
      - ./logs:/app/logs
      - ./web_working/logs:/app/web_working/logs
      # Persist session data
      - ./session_data:/app/session_data
    environment:
      # Optional: Add environment variables here
      - PYTHONUNBUFFERED=1
    network_mode: host  # Use host network - ports 3000, 5000, 5001 automatically exposed
    restart: unless-stopped
